name: mmc
description: 这是一个商圈app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.51+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  auto_route: ^3.2.0
#  permission_handler: ^8.1.6
  provider: ^6.0.1
  dio: ^4.0.0
  dio_log: ^2.0.0
  badges: ^2.0.1
  flutter_easyrefresh: ^2.2.1
  lottie: ^1.0.1
  fluttertoast: ^8.0.7
  flutter_easyloading: ^3.0.0
  keyboard_actions: ^3.4.0
  animations: ^2.0.0
  simple_animations: ^3.1.1
  event_bus: ^2.0.0
  cached_network_image: ^3.0.0
  table_calendar: ^3.0.3
  chewie: ^1.2.2
  # 链接处理，可用于拨打电话
  url_launcher: ^6.0.9
  # 常用工具类库
  flustars: ^2.0.1
  # 桌面应用图标角标
  flutter_app_badger: ^1.3.0
  # 滚轮选择器
  flutter_pickers: ^2.1.1
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.6.1
  # listView 侧滑菜单
  flutter_slidable: ^0.6.0
  flutter_local_notifications: ^9.1.5
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  webview_flutter: ^2.3.1
  flutter_html: ^2.1.5
  photo_view: ^0.13.0
  package_info: ^2.0.2
dependency_overrides:
  provider: ^6.0.1
  flutter_math_fork: ^0.6.0
  flutter_svg: ^1.0.0
  decimal: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  # 闪屏及桌面图标
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.2
  auto_route_generator: ^3.2.0
  build_runner:

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/font/NotoSans-Regular.ttf
        - asset: assets/font/NotoSans-Bold.ttf
        - asset: assets/font/NotoSans-Italic.ttf
        - asset: assets/font/NotoSans-BoldItalic.ttf
  assets:
   # image
   - assets/image/head.png
   - assets/image/logo.png
   - assets/image/login_e1.png
   - assets/image/login_e2.png
   - assets/image/login_c.png
   - assets/image/profile_logo_bg.png
   - assets/image/profile_default.png
   - assets/image/profile_z.png
   - assets/image/personal_head_empty.png
   - assets/image/app_launch.png
   - assets/image/404.png
   - assets/image/err_net.png
   - assets/image/no_data.png
   - assets/image/login_background.png
   - assets/image/profile_e.png
   - assets/image/profile_m.png
   - assets/image/profile_p.png
   - assets/image/profile_pla.png
   - assets/image/profile_t.png
   # icon图标
   - assets/icon/home.png
   - assets/icon/network.png
   - assets/icon/check_in.png
   - assets/icon/profile.png
   - assets/icon/login_password_eye_close.png
   - assets/icon/login_password_eye_open.png
   - assets/icon/app_bar_filter.png
   - assets/icon/app_bar_ring.png
   - assets/icon/app_bar_set.png
   - assets/icon/menu_event.png
   - assets/icon/menu_group.png
   - assets/icon/menu_send_referral.png
   - assets/icon/menu_shining_board.png
   - assets/icon/menu_send_thank_note.png
   - assets/icon/menu_referral_received.png
   - assets/icon/menu_thank_you_note_received.png
   - assets/icon/menu_shop.png
   - assets/icon/note.png
   - assets/icon/date.png
   - assets/icon/group_user_grade_1.png
   - assets/icon/group_user_grade_2.png
   - assets/icon/group_user_grade_3.png
   - assets/icon/group_user_grade_4.png
   - assets/icon/item_like.png
   - assets/icon/item_no_like.png
   - assets/icon/form_required.png
   - assets/icon/item_down.png
   - assets/icon/item_up.png
   - assets/icon/call.png
   - assets/icon/wechat.png
   - assets/icon/facebook.png
   - assets/icon/in.png
   - assets/icon/video.png
   - assets/icon/photo_mei.png
   - assets/icon/change.png
   - assets/icon/set_personal_profile.png
   - assets/icon/set_business_profile.png
   - assets/icon/set_change_password.png
   - assets/icon/set_guideline.png
   - assets/icon/set_about_us.png
   - assets/icon/set_new_user_tour.png
   - assets/icon/set_privacy_policy.png
   - assets/icon/set_term_of_service.png
   - assets/icon/set_language.png
   - assets/icon/thank_you_z.png
   - assets/icon/thank_you_send.png
   - assets/icon/most_referral_sent.png
   - assets/icon/most_referral_received.png
   - assets/icon/thank_you_note.png
   - assets/icon/event_supporter.png
   - assets/icon/rank_1.png
   - assets/icon/rank_2.png
   - assets/icon/rank_3.png
   - assets/icon/profile_my_group.png
   - assets/icon/profile_my_network.png
   - assets/icon/profile_your_pic.png
   - assets/icon/upcoming_item_ic.png
   - assets/icon/check_in_log.png
   - assets/icon/check_out.png
   - assets/icon/notic_home.png
   - assets/icon/notic_message.png
   - assets/icon/notic_mony.png
   - assets/icon/notic_new.png
   - assets/icon/notic_system.png
   # lottie动画
   - assets/lottie/loading.json
   # json
   - assets/json/countries.json
# 生成app图标 flutter clean && flutter pub get && flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/image/logo.png

# 生成闪屏页 flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
# 移除闪屏页 flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/image/app_launch.png
  android: true
  ios: true
  #web: false
  android_gravity: fill
  ios_content_mode: scaleToFill
  fullscreen: true

